# Generated by Django 2.0.6 on 2018-06-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': '校区', 'verbose_name_plural': '校区'},
        ),
        migrations.AlterModelOptions(
            name='classlist',
            options={'verbose_name': '班级', 'verbose_name_plural': '班级'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='courserecord',
            options={'verbose_name': '上课记录', 'verbose_name_plural': '上课记录'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户', 'verbose_name_plural': '客户'},
        ),
        migrations.AlterModelOptions(
            name='customerfollowup',
            options={'verbose_name': '客户跟进', 'verbose_name_plural': '客户跟进'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': '报名', 'verbose_name_plural': '报名'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': '缴费记录', 'verbose_name_plural': '缴费记录'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
        migrations.AlterModelOptions(
            name='studyrecord',
            options={'verbose_name': '学习记录', 'verbose_name_plural': '学习记录'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': '账号'},
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '已报名'), (1, '未报名'), (2, '已退学')], default=0),
        ),
        migrations.AddField(
            model_name='customerfollowup',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '绝无报名计划'), (1, '一个月内报名'), (2, '2周内报名'), (3, '已报名其它机构')], default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(to='CRM.Tag'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(to='CRM.Role'),
        ),
        migrations.AlterUniqueTogether(
            name='studyrecord',
            unique_together={('student', 'course_record')},
        ),
    ]
